### ISSUE TITLE
Update the web-shell image to escape the Safari problem with font color

### ISSUE THREAD

**Issue by eviltwinhans** [neuro-inc/neuro-web-shell#44]
Terminal in Safari looks like a completely black screen because font and background are of the same color.

![Screenshot at Dec 16 17-03-40](https://user-images.githubusercontent.com/22771839/146559016-f9fc300b-f357-4b55-b0f9-027f0235a835.png)

Chrome and FF are fine.

![Screenshot at Dec 16 16-52-19](https://user-images.githubusercontent.com/22771839/146559200-778108b8-5779-4ed9-a5c0-2d83a999fa9e.png)

**Comment by anayden** [comment]
Works now

**Comment by YevheniiSemendiak** [comment]
Not in my case, 
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/32543098/164479472-e8ce4b58-be31-4976-8497-fa8f352a892c.png">
Which version of Safary you have?
Mine is Version 15.2 (17612.3.6.1.6)
OS: macOS 12.1 (21C52)

**Comment by anayden** [comment]
Safari `Version 15.4 (17613.1.17.1.6)`
MacOS `12.3 (21E230)`

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/17383/164480021-9cefd7ed-289a-4c1f-bf93-47eec4a555e1.png">

**Comment by YevheniiSemendiak** [comment]
ok, will try again after the update

**Comment by YevheniiSemendiak** [comment]
The update helped cc @eviltwinhans
